function display(self)
    disp(['%# =' class(self)])
    disp(['%#.xy=' class(self.xy)])
    disp(['%#.text=' serialize(self.text)])
    disp(['%#.fontname=' serialize(self.fontname)])
    disp(['%#.fontsize=' serialize(self.fontsize)])
    disp(['%#.fontweight=' serialize(self.fontweight)])
    disp(['%#.fontangle=' serialize(self.fontangle)])
    disp(['%#.horizontalalignment=' serialize(self.horizontalalignment)])
    disp(['%#.verticalalignment=' serialize(self.verticalalignment)])
    disp(['%#.backgroundcolor=' serialize(self.backgroundcolor)])
    disp(['%#.interpreter=' serialize(self.interpreter)])
    display(self.GPath)
end