% Create a slider control. 
%
% Use as
% function testslider
% function slider_callback(i)
%         disp(['Num ' num2str(i)])
% end
%     SliderControl(0,'X variable',1,313,13/2,@slider_callback)
% end
function h1=SliderControl(Parent,Name,Min,Max,Value,Step,Callback,rounding)
if (~exist('rounding','var')),rounding =0;end

if (Parent==0)
    h1 = figure('parent', Parent,...
        'Units','characters',...
        'IntegerHandle','off',...
        'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
        'MenuBar','none',...
        'Name',Name,...
        'NumberTitle','off',...
        'PaperPosition',get(0,'defaultfigurePaperPosition'),...
        'Position',[10 4 33 17],...
        'Renderer',get(0,'defaultfigureRenderer'),...
        'RendererMode','manual',...
        'Resize','off',...
        'HandleVisibility','callback',...
        'DeleteFcn',@close_down_callback,...
        'Tag','figure1',...
        'UserData',[],...
        'Visible','on');
else
    h1 = Parent;
end

slider = [];

edit_entry = uicontrol(...
    'Parent',h1,...
    'Units','characters',...
    'BackgroundColor',[1 1 1],...
    'Callback',@entry_callback,...
    'Position',[23.8 7.61538461538461 6.2 1.61538461538462],...
    'String',num2str(Value),...
    'Style','edit',...
    'Tag','edit_entry');

    function close_down_callback(hObject, eventdata)
        
    end

    function slider_callback(hObject, eventdata)
        Value=get(hObject,'Value');
        Min=get(hObject,'Min');
        Max=get(hObject,'Max');
        if (rounding)
            set(edit_entry,'String', num2str(round(Value)));
            Callback(round(Value));
        else
            set(edit_entry,'String', num2str((Value)));
            Callback((Value));
        end
    end

if (isempty(Step))
    Step =[1,1]/(double(Max)-double(Min));
end
if (length(Step)~=2)
    Step = [Step(1),Step(1)];
end
slider = uicontrol(...
    'Parent',h1,...
    'Units','characters',...
    'Callback',@slider_callback,...
    'Position',[16.8 0.769230769230766 5 15.3846153846154],...
    'String',{  'Slider' },...
    'Style','slider','SliderStep',Step,'Max',double(Max),'Min',double(Min),'Value',double(Value),...
    'Tag','slider');

    function entry_callback(hObject, eventdata)
        Value=get(hObject,'String');
        try
            Value =str2num(Value);
            if (Value <Min),  Value =  Min; end
            if (Value >Max),  Value =  Max; end
            if (rounding)
            set(edit_entry,'String', num2str(round(Value)));
            set(slider,'Value',round(Value));
            Callback(round(Value));
            else
            set(edit_entry,'String', num2str((Value)));
            set(slider,'Value',(Value));
            Callback((Value));
            end
        catch
        end
    end

ShortName  =  Name;;
if (length(Name )>10)
    ShortName =  [Name(1:7),'...'];
end

label = uicontrol(...
    'Parent',h1,...
    'Units','characters',...
    'Position',[2. 7.61538461538461 12.2 4.61538461538462],...
    'String', Name,...
    'BackgroundColor',[1 1 1],...
    'TooltipString', Name,...
    'Style','text',...
    'Tag','text_label');
[outstring,newpos] = textwrap(label,{Name}); %#ok<NOPRT>

set(label,'String',outstring,'Position',newpos);;

h3 = uicontrol(...
    'Parent',h1,...
    'Units','characters',...
    'Position',[23.8 14.5384615384615 6.2 1.61538461538462],...
    'String', num2str(Max) ,...
    'BackgroundColor',[1 1 1],...
    'Style','text',...
    'Tag','text_max');

h4 = uicontrol(...
    'Parent',h1,...
    'Units','characters',...
    'Position',[23.8 0.692307692307688 6.2 1.61538461538462],...
    'String', num2str(Min) ,...
    'BackgroundColor',[1 1 1],...
    'Style','text',...
    'Tag','text_min');


end